### ISSUE TITLE
No module named 'kafka.vendor.six.moves'

### ISSUE THREAD

**Issue by hamsunwoo** [Team1-TU-tech/airflow#15]
## 에러메세지
```bash
Traceback (most recent call last):
[2024-11-25, 07:28:16 UTC] {process_utils.py:194} INFO -   File "/tmp/venv-calltyq4z5y_/script.py", line 119, in <module>
[2024-11-25, 07:28:16 UTC] {process_utils.py:194} INFO -     res = upload_to_s3(*arg_dict["args"], **arg_dict["kwargs"])
[2024-11-25, 07:28:16 UTC] {process_utils.py:194} INFO -           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-11-25, 07:28:16 UTC] {process_utils.py:194} INFO -   File "/tmp/venv-calltyq4z5y_/script.py", line 44, in upload_to_s3
[2024-11-25, 07:28:16 UTC] {process_utils.py:194} INFO -     from kafka import KafkaProducer
[2024-11-25, 07:28:16 UTC] {process_utils.py:194} INFO -   File "/tmp/venv0vfsa4nr/lib/python3.12/site-packages/kafka/__init__.py", line 23, in <module>
[2024-11-25, 07:28:16 UTC] {process_utils.py:194} INFO -     from kafka.consumer import KafkaConsumer
[2024-11-25, 07:28:16 UTC] {process_utils.py:194} INFO -   File "/tmp/venv0vfsa4nr/lib/python3.12/site-packages/kafka/consumer/__init__.py", line 3, in <module>
[2024-11-25, 07:28:16 UTC] {process_utils.py:194} INFO -     from kafka.consumer.group import KafkaConsumer
[2024-11-25, 07:28:16 UTC] {process_utils.py:194} INFO -   File "/tmp/venv0vfsa4nr/lib/python3.12/site-packages/kafka/consumer/group.py", line 13, in <module>
[2024-11-25, 07:28:16 UTC] {process_utils.py:194} INFO -     from kafka.consumer.fetcher import Fetcher
[2024-11-25, 07:28:16 UTC] {process_utils.py:194} INFO -   File "/tmp/venv0vfsa4nr/lib/python3.12/site-packages/kafka/consumer/fetcher.py", line 19, in <module>
[2024-11-25, 07:28:16 UTC] {process_utils.py:194} INFO -     from kafka.record import MemoryRecords
[2024-11-25, 07:28:16 UTC] {process_utils.py:194} INFO -   File "/tmp/venv0vfsa4nr/lib/python3.12/site-packages/kafka/record/__init__.py", line 1, in <module>
[2024-11-25, 07:28:16 UTC] {process_utils.py:194} INFO -     from kafka.record.memory_records import MemoryRecords, MemoryRecordsBuilder
[2024-11-25, 07:28:16 UTC] {process_utils.py:194} INFO -   File "/tmp/venv0vfsa4nr/lib/python3.12/site-packages/kafka/record/memory_records.py", line 27, in <module>
[2024-11-25, 07:28:16 UTC] {process_utils.py:194} INFO -     from kafka.record.legacy_records import LegacyRecordBatch, LegacyRecordBatchBuilder
[2024-11-25, 07:28:16 UTC] {process_utils.py:194} INFO -   File "/tmp/venv0vfsa4nr/lib/python3.12/site-packages/kafka/record/legacy_records.py", line 50, in <module>
[2024-11-25, 07:28:16 UTC] {process_utils.py:194} INFO -     from kafka.codec import (
[2024-11-25, 07:28:16 UTC] {process_utils.py:194} INFO -   File "/tmp/venv0vfsa4nr/lib/python3.12/site-packages/kafka/codec.py", line 9, in <module>
[2024-11-25, 07:28:16 UTC] {process_utils.py:194} INFO -     from kafka.vendor.six.moves import range
[2024-11-25, 07:28:16 UTC] {process_utils.py:194} INFO - ModuleNotFoundError: No module named 'kafka.vendor.six.moves'
[2024-11-25, 07:28:17 UTC] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 505, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 870, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 588, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
No module named 'kafka.vendor.six.moves'
```

**Comment by hamsunwoo** [comment]
## 해결방법
https://www.reddit.com/r/apachekafka/comments/1f47pki/no_module_named_kafkavendorsixmoves/

## 코드
```bash
pip install git+https://github.com/dpkp/kafka-python.git
```
