### ISSUE TITLE
org.apache.zookeeper.ClientCnxn$SessionTimeoutException

### ISSUE THREAD

**Issue by hamsunwoo** [Team1-TU-tech/airflow#18]
## 에러메세지
```bash
org.apache.zookeeper.ClientCnxn$SessionTimeoutException: Client session timed out, have not heard from server in 13348ms for session id 0x0
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1258)
[2024-11-26 02:18:14,025] INFO Opening socket connection to server zookeeper1/172.23.0.3:2181. (org.apache.zookeeper.ClientCnxn)
[2024-11-26 02:18:14,025] INFO SASL config status: Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2024-11-26 02:18:25,730] ERROR Timed out waiting for connection to Zookeeper server [zookeeper1:2181,zookeeper2:2181,zookeeper3:2181]. (io.confluent.admin.utils.ClusterStatus)
[2024-11-26 02:18:27,365] WARN Client session timed out, have not heard from server in 13336ms for session id 0x0 (org.apache.zookeeper.ClientCnxn)
[2024-11-26 02:18:27,365] WARN An exception was thrown while closing send thread for session 0x0. (org.apache.zookeeper.ClientCnxn)
org.apache.zookeeper.ClientCnxn$SessionTimeoutException: Client session timed out, have not heard from server in 13336ms for session id 0x0
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1258)
```

**Comment by hamsunwoo** [comment]
## 원인
org.apache.zookeeper.ClientCnxn$SessionTimeoutException 오류는 Kafka와 ZooKeeper 간의 연결 문제를 나타냅니다. 주로 ZooKeeper 서버와 클라이언트(예: Kafka)의 연결이 일정 시간 동안 유지되지 않거나, 네트워크 장애로 인해 세션이 타임아웃되는 경우 발생합니다. 

## 해결방법 - 주키퍼 설정 조정
```bash
tickTime=2000
initLimit=10
syncLimit=5
```
